# Generated by Django 5.1.5 on 2026-01-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClinicalAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(max_length=100, unique=True)),
                ("timestamp", models.DateTimeField()),
                ("risk_level", models.CharField(max_length=20)),
                ("approval_required", models.BooleanField()),
                ("agents_executed", models.JSONField()),
                ("status", models.CharField(max_length=50)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
